// Pitch PWA service worker — generated by scripts/build-pwa.mjs, do not edit.
// Precaches the app shell (one self-contained page + manifest + icons) and serves it
// cache-first. Only same-origin GETs for those files and navigations within the app folder
// are handled; everything else (cross-origin, other paths) goes straight to the network and is
// never cached. Audio never passes through here: files are decoded in the page.
const VERSION = 'fabf353678a3';
const SCOPE = self.registration.scope;
const PREFIX = 'pitch-app:' + SCOPE + ':';
const CACHE = PREFIX + VERSION;
const PRECACHE = ["index.html","manifest.webmanifest","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-192.png","icons/icon-maskable-512.png","icons/apple-touch-icon.png"].map((p) => new URL(p, SCOPE).href);
const INDEX = PRECACHE[0];
const SHA256 = ["00fb900107b36d8efa385b67476705211c16a8bc47d7fc3d0515292a74b75fc4","8fd1d85733f119abdc37a87c7b92d81d7c5d14aba38be3fd0d838d1b9de7e461","74cf065916d6e80f95d603e6f7d739463e57eac8aa2936399c408b224578333e","8fd008887fc0db7ba5db70d5cf5d0fae98e003c01caedace798e5f0f49a9eac3","e172816c90f0feb56c725fff82cdedbb30191622b281bf6481659e6ff4753091","b3d898a80f2684c712d3201b51f86f6045290895684f9f9a9cea270d3e1f7c7c","273e4e3aca6c29c726f313c5aa8575b47dc08c3bdabe7ae12d19cbd6654f7f7d"];

const hex = (buf) => Array.from(new Uint8Array(buf), (b) => b.toString(16).padStart(2, '0')).join('');
const matches = async (res, i) => !!res && hex(await crypto.subtle.digest('SHA-256', await res.clone().arrayBuffer())) === SHA256[i];
// The cached page, only if it is byte-identical to this build's index.html.
const cachedIndex = async (cache) => { const hit = await cache.match(INDEX); return (await matches(hit, 0)) ? hit : null; };

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    try {
      await Promise.all(PRECACHE.map(async (url, i) => {
        // ?v= misses any CDN copy of an older deploy; stored under the plain URL.
        const res = await fetch(url + '?v=' + VERSION, { cache: 'reload' });
        if (!res.ok || res.redirected || !(await matches(res, i))) throw new Error('precache: unexpected response for ' + url);
        await cache.put(url, res);
      }));
    } catch (err) {
      await caches.delete(CACHE); // no half-filled cache left behind; the old version stays active
      throw err;
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.href.startsWith(SCOPE)) return;
  const path = url.origin + url.pathname;

  // Navigations to the app folder itself (./, ./index.html, ./?…, ./other.html): the app
  // shell is served for these, cache-first for the app URL, network-then-cache for the
  // rest. Deeper paths are left alone — the page's relative URLs would not resolve there.
  if (req.mode === 'navigate') {
    if (url.pathname.slice(new URL(SCOPE).pathname.length).includes('/')) return;
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      if (path === SCOPE || path === INDEX) {
        const hit = await cachedIndex(cache);
        if (hit) return hit;
      }
      try {
        return await fetch(req);
      } catch (err) {
        const hit = await cachedIndex(cache);
        if (hit) return hit;
        throw err;
      }
    })());
    return;
  }

  // Cache Storage is shared by every page on the origin (other products under the same
  // github.io host), so a cached copy is used only if it matches this build's hash.
  const i = PRECACHE.indexOf(path);
  if (i < 0) return;
  event.respondWith((async () => {
    const hit = await (await caches.open(CACHE)).match(path);
    return (await matches(hit, i)) ? hit : fetch(req);
  })());
});
