// Cloudflare Workers entry (wrangler.jsonc "main"). Wraps the worker generated by
// `opennextjs-cloudflare build` and adds a `scheduled` handler so the Cron Trigger
// in wrangler.jsonc runs the same hourly check Vercel runs via vercel.json (split
// into per-minute slices, see lib/guard/cron.ts).
// https://opennext.js.org/cloudflare/howtos/custom-worker
//
// Not used by `next build` / Vercel. Types are declared locally so `tsc` passes
// before .open-next/ exists and without pulling the Workers runtime types into the app.

// @ts-ignore `.open-next/worker.js` is generated at build time
import { default as handler } from "./.open-next/worker.js";
// @ts-ignore generated at build time. Evaluate the Next.js server at isolate startup
// (1 s startup budget) instead of inside the first dynamic request (10 ms CPU budget).
import "./.open-next/server-functions/default/handler.mjs";
// The cron slice runs without Next.js (bundled separately by wrangler; evaluated at startup).
import { cronBatchSize, runCronSlice } from "./lib/guard/cron";
import { getKV } from "./lib/redis";

type Env = Record<string, unknown>;
type Ctx = { waitUntil(p: Promise<unknown>): void; passThroughOnException(): void };
type OpenNextHandler = { fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> };
type ScheduledController = { cron: string; scheduledTime: number };

/**
 * Cron: one small slice of the hourly check per run (lib/guard/cron.ts), called
 * directly — not through the Next.js route — so a run costs only the check itself
 * (no Next request handling, ~4–5 ms), even in a fresh isolate. With the
 * `* * * * *` trigger and CRON_BATCH_SIZE (wrangler.jsonc) that is up to 60 runs an hour.
 * Failures are thrown so they show as failed invocations in the Cron Events log.
 */
async function runCron(controller: ScheduledController, env: Env): Promise<void> {
  // process.env carries vars/secrets (nodejs_compat); prefer the binding values explicitly.
  for (const [k, v] of Object.entries(env)) if (typeof v === "string") process.env[k] = v;
  const result = await runCronSlice(getKV(), { now: new Date(controller.scheduledTime), batch: cronBatchSize() });
  const line = `[cron] ${controller.cron} ${JSON.stringify(result)}`;
  if (result.errors) throw new Error(line);
  console.log(line);
}

/**
 * Rate limits key on the client IP (lib/ratelimit.ts reads x-forwarded-for). On
 * Cloudflare the client can prepend its own x-forwarded-for entries, but
 * cf-connecting-ip is always set by Cloudflare, so pin x-forwarded-for to it.
 */
function withClientIp(request: Request): Request {
  const ip = request.headers.get("cf-connecting-ip");
  if (!ip) return request;
  const headers = new Headers(request.headers);
  headers.set("x-forwarded-for", ip);
  headers.set("x-real-ip", ip);
  return new Request(request, { headers });
}

export default {
  fetch: (request: Request, env: Env, ctx: Ctx) => (handler as OpenNextHandler).fetch(withClientIp(request), env, ctx),
  async scheduled(controller: ScheduledController, env: Env) {
    await runCron(controller, env);
  },
};
