// Cloudflare Workers entry (wrangler.jsonc "main"). Wraps the worker generated by
// `opennextjs-cloudflare build` and adds a `scheduled` handler so the Cron Trigger
// in wrangler.jsonc runs the same hourly check Vercel runs via vercel.json.
// https://opennext.js.org/cloudflare/howtos/custom-worker
//
// Not used by `next build` / Vercel. Types are declared locally so `tsc` passes
// before .open-next/ exists and without pulling the Workers runtime types into the app.

// @ts-ignore `.open-next/worker.js` is generated at build time
import { default as handler } from "./.open-next/worker.js";

type Env = { CRON_SECRET?: string } & Record<string, unknown>;
type Ctx = { waitUntil(p: Promise<unknown>): void; passThroughOnException(): void };
type OpenNextHandler = { fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> };
type ScheduledController = { cron: string; scheduledTime: number };

// Keep non-handler values unexported: workerd treats every named export as a handler.
const CRON_PATH = "/api/cron/check";

/**
 * Calls the Next.js route in-process (handler.fetch, not a network fetch), so it
 * doesn't count as a subrequest and needs no public hostname. The route checks
 * `Authorization: Bearer $CRON_SECRET` exactly as on Vercel.
 */
async function runCron(controller: ScheduledController, env: Env, ctx: Ctx): Promise<void> {
  if (!env.CRON_SECRET) {
    console.error("[cron] CRON_SECRET is not set; /api/cron/check would reject the call (401). Run: wrangler secret put CRON_SECRET");
    return;
  }
  const request = new Request(`https://budget-guard.internal${CRON_PATH}`, {
    headers: { authorization: `Bearer ${env.CRON_SECRET}`, "user-agent": "cloudflare-cron" },
  });
  const res = await (handler as OpenNextHandler).fetch(request, env, ctx);
  const body = await res.text();
  const line = `[cron] ${controller.cron} → ${CRON_PATH} ${res.status} ${body.slice(0, 500)}`;
  if (res.ok) console.log(line);
  else throw new Error(line); // surfaces as a failed invocation in the Cron Events log
}

export default {
  fetch: (handler as OpenNextHandler).fetch,
  async scheduled(controller: ScheduledController, env: Env, ctx: Ctx) {
    await runCron(controller, env, ctx);
  },
};
